# Generated by Django 3.2.8 on 2021-10-17 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('member_number', models.IntegerField(blank=True, null=True)),
                ('date_of_membership', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signature/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_month_balance', models.IntegerField()),
                ('first_weak', models.IntegerField(blank=True, null=True)),
                ('second_weak', models.IntegerField(blank=True, null=True)),
                ('third_weak', models.IntegerField(blank=True, null=True)),
                ('fourth_weak', models.IntegerField(blank=True, null=True)),
                ('fifth_weak', models.IntegerField(blank=True, null=True)),
                ('savings_of_this_month', models.IntegerField(blank=True, null=True)),
                ('total_savings', models.IntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
        ),
    ]
