# Generated by Django 3.2.8 on 2021-10-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='previous_month_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
