def months(name):
    if name=="January":
        return 1
    elif name=="February":
        return 2
    elif name=="March":
        return 3
    elif name=="April":
        return 4
    elif name=="May":
        return 5
    elif name=="June":
        return 6
    elif name=="July":
        return 7
    elif name=="August":
        return 8
    elif name=="September":
        return 9
    elif name=="October":
        return 10
    elif name=="November":
        return 11
    elif name=="December":
        return 12

